### ISSUE TITLE
Questions regarding WF macroscope protocol

### ISSUE THREAD

**Issue by acbandi** [musall/WidefieldImager#1]
Hi Simon, 

I ran the code (below) you provided on Matlab 2014b and got this error: Undefined function 'contains' for input arguments of type 'cell'. I think this is because Matlab 2014b does not have 'contains' as native function. 

    info = imaqhwinfo;
    camCheck = contains(info.InstalledAdaptors, 'pcocameraadaptor');
    vidName = info.InstalledAdaptors{camCheck}; %PCO camera
    
    vidObj = videoinput(vidName); %get video object  %had to change adaptorName to vidName
    src = getselectedsource(vidObj);
    
        clockSpeed = set(src,'PCPixelclock_Hz');
        [~,idx] = max(str2num(cell2mat(clockSpeed))); %get fastest clockspeed
        src.PCPixelclock_Hz = clockSpeed{idx}; %fast scanning mode
        src.E2ExposureTime = 1000/str2double(handles.FrameRate.String) * 1000; %set framerate
        binFact = 4; %set 4x binning by default
           
        try %uses different string in different adaptor versions...
            src.B1BinningHorizontal = num2str(binFact);
            src.B2BinningVertical = num2str(binFact);
        catch
            src.B1BinningHorizontal = num2str(binFact,'%02i');
            src.B2BinningVertical = num2str(binFact,'%02i');
        end
    
    figure
    preview(vidObj)

I then ran the code on Matlab 2016b and got this error: 

    Error using cat
    Dimensions of matrices being concatenated are not consistent.
    
    Error in cell2mat (line 83)
                m{n} = cat(1,c{:,n});

The camera does seem to load but there seems to be an issue on line 9 of the code. 

- Akhil

**Comment by musall** [comment]
Hi Akhil,

as you suggested, the error in 2014b seems to arise from the fact that you don't have the 'contains' function in that release. You should be able to resolve this issue by replacing the corresponding line in the Widefieldimager code with the code below:

replace the lines

camCheck = contains(info.InstalledAdaptors, 'pcocameraadaptor');
vidName = info.InstalledAdaptors{camCheck}; %PCO camera

with the lines below to identify the camera correctly

adaptors = info.InstalledAdaptors;
testName = 'pcocameraadaptor';
vidName = [];
for x = 1 : length(adaptors)
    if sum(ismember(adaptors{x}, testName)) == length(testName)
        vidName = adaptors{x}; %PCO camera
        break;
    end
end

**Comment by musall** [comment]
To resolve the second issue under Matlab2016, I would need more information. Can you stop in the debugger and post the contents of the 'src' object and the variable 'clockSpeed' ?

**Comment by acbandi** [comment]
Hi Simon, 

Thanks for the response! Unfortunately even after replacing the code in WidefieldImager in Matlab 2014b, I get the same issue:

 Warning: No camera found. Type "imaqhwinfo" to make sure your camera is porperly installed and running. 
> In WidefieldImager>WidefieldImager_OpeningFcn at 116
  In gui_mainfcn at 220
  In WidefieldImager at 42 

Using imaqhwinfo it does confirm that 'pcocameraadaptor' is not installed, but rather 'pcocameraadaptor_r2014b_x64', which is the adaptor provided by PCO for matlab 2014b. Even after replacing the installed adaptor name with 'pcocameraadaptor_r2014b_x64' it seems like it is still not finding the camera object. 

I will also test this on 2016b in addition to the suggestions you had for 2016b and will update you on that. 

Thanks, 

Akhil

**Comment by musall** [comment]
Hi Akhil,

if you can use 2016b, it would be better to focus on that version since we had checked compatibility for 2016 and earlier in our lab. That should make it easier with resolving your issues. If it doesn't work on 2016, it would be helpful if you could post as much information as possible about the error and the content of the involved variables so I can advise on how to fix it.

Best,
Simon

**Comment by acbandi** [comment]
Hi Simon, 

I ran WidefieldImager on 2016b and had the same issue: pcocameraadaptor was not detected and then I had to select pcocameraadaptor_r2016b from the 'select camera' menu. After selecting the pcocameraadaptor_r2016b the WidefieldImager GUI does open but I still get the message below:

Warning: No camera found. Type "imaqhwinfo" to make sure your
camera is porperly installed and running. 
> In WidefieldImager>WidefieldImager_OpeningFcn (line 116)
  In gui_mainfcn (line 220)
  In WidefieldImager (line 42) 

Next, I ran the code you provided earlier in 2016b. I have attached the contents of the src object below. 
![src](https://user-images.githubusercontent.com/55207539/172011772-6b35e8c3-7c59-4fdf-84d9-3d00cf0fbb37.PNG)

For clockspeed I get a 2x1 cell with the following numbers: 95333333, 286000000. 

![clockspeed](https://user-images.githubusercontent.com/55207539/172011979-11b0930f-63b2-4e51-ad06-ec7632d962d6.PNG)

This is where the error using cat occurs (line 9) 

Additionally, here is the contents of the vidObj object:
![vidObj](https://user-images.githubusercontent.com/55207539/172011878-eedd7067-cd2f-4a09-83f6-9586860d3179.PNG)

Let me know if you require more information. Thanks! 

- Akhil

**Comment by musall** [comment]
Hi Akhil,

It seems like your version of the pcoadapter contains the clockspeed of the camera in a different format as in the ones we have tested before. I just pushed a new version of the code that should avoid the issue. Can you try the new version on 2016b and let me know if anything changes?

If you still get the same error, please run the code below and let me know the result.


    info = imaqhwinfo;
    camCheck = contains(info.InstalledAdaptors, 'pcocameraadaptor');
    vidName = info.InstalledAdaptors{camCheck}; %PCO camera
    
    vidObj = videoinput(vidName); %get video object  %had to change adaptorName to vidName
    src = getselectedsource(vidObj);

    clockSpeed = set(src,'PCPixelclock_Hz');
    [~,idx] = max(cellfun(@str2num,clockSpeed)); %get fastest clockspeed
    src.PCPixelclock_Hz = clockSpeed{idx}; %fast scanning mode
    src.E2ExposureTime = 1000/str2double(handles.FrameRate.String) * 1000; %set framerate
    binFact = 4; %set 4x binning by default
       
    try %uses different string in different adaptor versions...
        src.B1BinningHorizontal = num2str(binFact);
        src.B2BinningVertical = num2str(binFact);
    catch
        src.B1BinningHorizontal = num2str(binFact,'%02i');
        src.B2BinningVertical = num2str(binFact,'%02i');
    end

    figure
    preview(vidObj)

**Comment by acbandi213** [comment]
Hi Simon, 

The new version is working! Looks like bypassing the clock speed with the pcoadaptor worked. 

Thanks so much for all your help! 

- Akhil

**Comment by musall** [comment]
That's great, I will close this issue then.
The problem was that the pcoadapter reported the clockspeed as a column instead of a row vector. 
The new version can deal with that and should work just the same.
